

create or replace TABLE HIMS.SQL_RAW.Appointment (
	APPOINTMENTID int,
	DOCTORID int,
	PATIENTID int,
	DATEOFAPPOINTMENT TIMESTAMP_NTZ(9),
	DATEADDED TIMESTAMP_NTZ(9),
	ADDEDBY VARCHAR(100),
	DATELASTMODIFIED TIMESTAMP_NTZ(9),
	MODIFIEDBY VARCHAR(100)
);