create or replace TABLE HIMS.SQL_RAW.Speciality (
	SPECIALITYID int,
	DESCRIPTION VARCHAR(100),
	DATEADDED TIMESTAMP_NTZ(9),
	ADDEDBY VARCHAR(100),
	DATELASTMODIFIED TIMESTAMP_NTZ(9),
	MODIFIEDBY VARCHAR(100)
);
